### ISSUE TITLE
Warning: Error in InsertionBias.ChromatinAssay: Not all hexamers represented in input region

### ISSUE THREAD

**Issue by luoyyyy** [stuart-lab/signac#1713] opened 2024-05-30 13:08 UTC
pbmcs <<- Footprint(pbmcs, motif.name="MA0634.1" ,genome=BSgenome.Hsapiens.NCBI.GRCh38)

data_source:
Library strategy	ATAC-seq
Library source	transcriptomic single cell
Library selection	other
Instrument model	Illumina NovaSeq 6000

Description	Single-cell ATAC sequencing (10xGenomics Chromium)
Chr-Veh_R1
Data processing	Count matrices, fragment files and associated metadata were produced from fastq files using 10x Genomics Cell Ranger ATAC v2.0.0 with the reference GRCh38 (Ensembl release 94).
Aggregated count matrices, fragment files and associated metadata over all samples were geneated using the "cellranger-atac aggr" command with the reference "homo_sapiens_GRCh38_ensrel94_cr2_0_0".
Assembly: hg38
Supplementary files format and content: filtered_peak_bc_matrix.h5: CellRanger output HDF5 file containing the filtered barcodes x peaks count matrix.
Supplementary files format and content: fragments.tsv.gz: CellRanger output compressed tab-delimited text file containing one line per unique observed ATAC-seq fragment.
Supplementary files format and content: fragments.tsv.gz.tbi: CellRanger output tabix index file for the fragments.tsv.gz file.
Supplementary files format and content: singlecell.csv: CellRanger output comma-separated text file containing per-barcode metadata.

> head(Fragments(pbmcs)[[1]])
  chrom start   end            barcode readCount
1     1 10061 10346 GGCACGTAGAGCCTGA-1         1
2     1 10072 10526 CACAACACACATGATC-1         1
3     1 10073 10279 GAGAACGAGGATTGCG-1         1
4     1 10073 10309 CTTGCCACAGGTGGTA-1         1
5     1 10073 10589 GGTAGGAAGATGGGAA-1         1
6     1 10079 10333 TGGCCTTCAAACCTAC-1         1

FootPrinting! 
ChromatinAssay data with 268284 features for 3305 cells
Variable features: 268284 
Genome: 
Annotation present: TRUE 
Motifs present: TRUE 
Fragment files: 1 
.....................Extracting reads in requested region
Warning: Error in InsertionBias.ChromatinAssay: Not all hexamers represented in input region
  50: stop
  49: InsertionBias.ChromatinAssay
  47: InsertionBias.Seurat

The reasons for the  errors, and how should I do?

**Comment by timoast** [comment] 2024-06-13 08:50
Hi, there is no error message here, just a warning stating that not all hexamers were present in the region of DNA being used for the InsertionBias function. Is there an error that you're encountering? Appreciate if you could also provide your `sessionInfo()` information and complete code

**Comment by timoast** [comment] 2024-06-14 01:23
Can you provide the full code?

**Comment by luoyyyy** [comment] 2024-06-14 03:27
library(Signac)
library(Seurat)
library(EnsDb.Hsapiens.v86)
library(ggplot2)
library(patchwork)
library(JASPAR2020)
library(TFBSTools)
library(patchwork)
library(BSgenome.Hsapiens.NCBI.GRCh38)
library(biovizBase)
library(hdf5r)

counts <- Read10X_h5(filename = "D:/R/R project/SignacShiny-11-9-zc/data/chr1/GSM8002547_Chr-Veh_R1_filtered_peak_bc_matrix.h5")
metadata <- read.csv(
  file = "D:/R/R project/SignacShiny-11-9-zc/data/chr1/GSM8002547_Chr-Veh_R1_singlecell.csv",
  header = TRUE,
  row.names = 1
)

chrom_assay <- CreateChromatinAssay(
  counts = counts,
  sep = c(":", "-"),
  fragments = 'D:/R/R project/SignacShiny-11-9-zc/data/chr1/GSM8002547_Chr-Veh_R1_fragments.tsv.gz',
  min.cells = 10,
  min.features = 200
)

pbmc <- CreateSeuratObject(
  counts = chrom_assay,
  assay = "peaks",
  meta.data = metadata
)
pbmc
pbmc[['peaks']]
granges(pbmc)# extract gene annotations from EnsDb
annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v86)

# change to UCSC style since the data was mapped to hg19
#seqlevels(annotations) <- paste0('chr', seqlevels(annotations))
genome(annotations) <- "GRCH38"
# add the gene information to the object
Annotation(pbmc) <- annotations
# compute nucleosome signal score per cell
pbmc <- NucleosomeSignal(object = pbmc)
pbmc
# compute TSS enrichment score per cell
pbmc <- TSSEnrichment(object = pbmc, fast = FALSE)
pbmc
# add blacklist ratio and fraction of reads in peaks
pbmc$pct_reads_in_peaks <- pbmc$peak_region_fragments / pbmc$passed_filters * 100
pbmc$blacklist_ratio <- pbmc$blacklist_region_fragments / pbmc$peak_region_fragments
DensityScatter(pbmc, x = 'nCount_peaks', y = 'TSS.enrichment', log_x = TRUE, quantiles = TRUE)
TSSPlot(pbmc) + NoLegend()
FragmentHistogram(object = pbmc,region = "1-1-2000000")
pbmc
VlnPlot(
  object = pbmc,
  features = c('nCount_peaks', 'TSS.enrichment', 'blacklist_ratio', 'nucleosome_signal', 'pct_reads_in_peaks'),
  pt.size = 0.1,
  ncol = 5
)
pbmc
pbmcs <- subset(
  x = pbmc,
  subset = peak_region_fragments > 3000 &
    peak_region_fragments < 30000 &
    pct_reads_in_peaks > 15 &
    blacklist_ratio < 0.05 &
    nucleosome_signal < 4 &
    TSS.enrichment >2
)
pbmcs
pbmcs <- RunTFIDF(pbmcs)
pbmcs <- FindTopFeatures(pbmcs, min.cutoff = 'q0')
pbmcs <- RunSVD(pbmcs)
DepthCor(pbmcs)

pbmcs <- RunUMAP(object = pbmcs, reduction = 'lsi', dims = 2:30)
pbmcs <- FindNeighbors(object = pbmcs, reduction = 'lsi', dims = 2:30)
pbmcs <- FindClusters(object = pbmcs, verbose = FALSE, algorithm = 3)
DimPlot(object = pbmcs, label = TRUE) + NoLegend()

gene.activities <- GeneActivity(pbmcs)
# add the gene activity matrix to the Seurat object as a new assay and normalize it
pbmcs[['RNA']] <- CreateAssayObject(counts = gene.activities)
pbmcs<- NormalizeData(
  object = pbmcs,
  assay = 'RNA',
  normalization.method = 'LogNormalize',
  scale.factor = median(pbmcs$nCount_RNA)
)

DefaultAssay(pbmcs) <- 'peaks'
FindAllMarkers_result <<- FindAllMarkers(pbmcs,  logfc.threshold = 0.25, assay = "peaks",
                                         min.pct = 0.7, only.pos = FALSE, verbose = T,
                                         test.use = "LR", latent.vars = 'nCount_peaks')
print(FindAllMarkers_result)
FindMarkers_result <- FindMarkers(
  object = pbmcs,
  ident.1 = 3,
  ident.2 =1,logfc.threshold = 0.25,
  test.use = 'LR',min.pct = 0.7, only.pos = FALSE,verbose = T,
  latent.vars ='nCount_peaks'
)

print(FindMarkers_result)
pfm <- TFBSTools::getMatrixSet(
  x = JASPAR2020,
  opts = list(collection = "CORE", species=9606, all_versions = FALSE)
)

# add motif information
pbmcs <- AddMotifs(
  object = pbmcs,
  genome = BSgenome.Hsapiens.NCBI.GRCh38,
  pfm = pfm
)
rm(pfm)
MotifTopMarkers1 <<- (FindAllMarkers_result %>% top_n(n = 10, wt = avg_log2FC))
enriched.motifs1 <<- FindMotifs(object = pbmcs,features = rownames(MotifTopMarkers1))
print(enriched.motifs1)
MotifTopMarkers2 <<- (FindMarkers_result %>% top_n(n = 10, wt = avg_log2FC))
enriched.motifs <- FindMotifs(object = pbmcs,features =enriched.motifs2)
MotifPlot(object = pbmcs,motifs = "ETV5")
pbmcs <<- Footprint(pbmcs, motif.name="ETV5" ,genome=BSgenome.Hsapiens.NCBI.GRCh38)
PlotFootprint(pbmcs, features = "ETV5")

**Comment by timoast** [comment] 2024-06-14 04:32
I think the problem is you are using the NCBI BSgenome but your peaks are likely in the UCSC chromosome naming format. Try using the UCSC genome instead: `BSgenome.Hsapiens.UCSC.hg38`

**Comment by luoyyyy** [comment] 2024-06-14 05:53
I using the UCSC genome :BSgenome.Hsapiens.UCSC.hg38,but that will have new problem
 # add motif information
> pbmcs <- AddMotifs(
+   object = pbmcs,
+   genome = BSgenome.Hsapiens.UCSC.hg38,
+   pfm = pfm
+ )
Building motif matrix
Warning in CreateMotifMatrix(features = object, pwm = pfm, genome = genome,  :
  Not all seqlevels present in supplied genome
Error in fixupDN.if.valid(value, x@Dim) : 
  length of Dimnames[[1]] (1) is not equal to Dim[1] (0)
In addition: Warning message:
In .merge_two_Seqinfo_objects(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)

**Comment by luoyyyy** [comment] 2024-06-14 06:23
And I think that should use NCBI  BSgenome
head(Fragments(pbmcs)[[1]])
chrom start end barcode readCount
1 1 10061 10346 GGCACGTAGAGCCTGA-1 1
2 1 10072 10526 CACAACACACATGATC-1 1
3 1 10073 10279 GAGAACGAGGATTGCG-1 1
4 1 10073 10309 CTTGCCACAGGTGGTA-1 1
5 1 10073 10589 GGTAGGAAGATGGGAA-1 1
6 1 10079 10333 TGGCCTTCAAACCTAC-1 1
> granges(pbmc)# extract gene annotations from EnsDb
GRanges object with 268284 ranges and 0 metadata columns:
             seqnames        ranges strand
                <Rle>     <IRanges>  <Rle>
       [1]          1 180982-181870      *
       [2]          1 183994-184853      *
       [3]          1 191031-191864      *
       [4]          1 629496-630393      *
       [5]          1 631266-632167      *
       ...        ...           ...    ...
  [268280] KI270711.1   22580-23439      *
  [268281] KI270713.1   15663-16539      *
  [268282] KI270713.1   21464-22364      *
  [268283] KI270713.1   25995-26809      *
  [268284] KI270713.1   28184-29088      *
  -------
  seqinfo: 33 sequences from an unspecified genome; no seqlengths

**Comment by timoast** [comment] 2024-06-14 09:07
Ok I looked into this with the dataset on GEO and it seems like there are some unusual base characters in that version of the genome that were causing some problems. This should now be fixed on the develop branch, please let me know if it works for you

**Closed** 2024-08-02 07:53 UTC
Labels: documentation
