### ISSUE TITLE
Error installing/loading Signac - Unable to load shared object .../Rsamtools.dll

### ISSUE THREAD

**Issue by roya-abs** [stuart-lab/signac#1246] opened 2022-10-13 16:57 UTC
Hi,

I tried to install Signac from CRAN and also github. But I got the following error while trying either one:

```
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/Users/fly/AppData/Local/R/win-library/4.2/Rsamtools/libs/x64/Rsamtools.dll':
  LoadLibrary failure:  The specified module could not be found.
```

It seems that it is something related to Rsamtools; so, I uninstalled and installed it again but again I got the same error. I am not sure whether it is something related to the package. 
I would appreciate any feedback.
Roya

SessionInfo

```
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 14393)

Matrix products: default

Random number generation:
 RNG:     L'Ecuyer-CMRG 
 Normal:  Inversion 
 Sample:  Rejection 
 
locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats4    grid      stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] scCustomize_0.7.0           SeuratDisk_0.0.0.9020      
 [3] rhdf5_2.40.0                plyr_1.8.7                 
 [5] gtable_0.3.1                gtools_3.9.3               
 [7] gridExtra_2.3               ArchR_1.0.2                
 [9] RCAv2_2.0.0                 Matrix_1.5-1               
[11] presto_1.0.0                data.table_1.14.2          
[13] Rcpp_1.0.9                  remotes_2.4.2              
[15] devtools_2.4.5              usethis_2.1.6              
[17] scater_1.24.0               scuttle_1.6.3              
[19] SingleCellExperiment_1.18.1 SummarizedExperiment_1.26.1
[21] Biobase_2.56.0              GenomicRanges_1.48.0       
[23] GenomeInfoDb_1.32.4         IRanges_2.30.1             
[25] S4Vectors_0.34.0            BiocGenerics_0.42.0        
[27] MatrixGenerics_1.8.1        matrixStats_0.62.0         
[29] ComplexHeatmap_2.12.1       fgsea_1.22.0               
[31] GSVA_1.44.5                 dittoSeq_1.8.1             
[33] escape_1.6.0                enrichR_3.1                
[35] dtwclust_5.5.11             dtw_1.23-1                 
[37] proxy_0.4-27                RColorBrewer_1.1-3         
[39] magrittr_2.0.3              forcats_0.5.2              
[41] stringr_1.4.1               purrr_0.3.5                
[43] tidyr_1.2.1                 tidyverse_1.3.2            
[45] dplyr_1.0.10                msigdbr_7.5.1              
[47] ggplot2_3.3.6               patchwork_1.1.2            
[49] sp_1.5-0                    SeuratObject_4.1.2         
[51] Seurat_4.2.0                tibble_3.1.8               
[53] readr_2.1.3                

loaded via a namespace (and not attached):
  [1] ggprism_1.0.3.9000        scattermore_0.8          
  [3] bit64_4.0.5               irlba_2.3.5.1            
  [5] DelayedArray_0.22.0       rpart_4.1.16             
  [7] doParallel_1.0.17         KEGGREST_1.36.3          
  [9] RCurl_1.98-1.9            generics_0.1.3           
 [11] ScaledMatrix_1.4.1        callr_3.7.2              
 [13] cowplot_1.1.1             RSQLite_2.2.18           
 [15] RANN_2.6.1                future_1.28.0            
 [17] bit_4.0.4                 tzdb_0.3.0               
 [19] spatstat.data_2.2-0       xml2_1.3.3               
 [21] lubridate_1.8.0           httpuv_1.6.6             
 [23] assertthat_0.2.1          viridis_0.6.2            
 [25] gargle_1.2.1              hms_1.1.2                
 [27] babelgene_22.9            promises_1.2.0.1         
 [29] fansi_1.0.3               dbplyr_2.2.1             
 [31] readxl_1.4.1              igraph_1.3.5             
 [33] DBI_1.1.3                 htmlwidgets_1.5.4        
 [35] spatstat.geom_2.4-0       googledrive_2.0.0        
 [37] paletteer_1.4.1           ellipsis_0.3.2           
 [39] RSpectra_0.16-1           ggpubr_0.4.0             
 [41] backports_1.4.1           annotate_1.74.0          
 [43] RcppParallel_5.1.5        deldir_1.0-6             
 [45] sparseMatrixStats_1.8.0   vctrs_0.4.2              
 [47] Cairo_1.6-0               ROCR_1.0-11              
 [49] abind_1.4-5               cachem_1.0.6             
 [51] withr_2.5.0               progressr_0.11.0         
 [53] sctransform_0.3.5         prettyunits_1.1.1        
 [55] goftest_1.2-3             cluster_2.1.3            
 [57] lazyeval_0.2.2            crayon_1.5.2             
 [59] hdf5r_1.3.7               pkgconfig_2.0.3          
 [61] pkgload_1.3.0             vipor_0.4.5              
 [63] nlme_3.1-157              rlang_1.0.6              
 [65] globals_0.16.1            lifecycle_1.0.3          
 [67] miniUI_0.1.1.1            modelr_0.1.9             
 [69] rsvd_1.0.5                cellranger_1.1.0         
 [71] rprojroot_2.0.3           polyclip_1.10-0          
 [73] lmtest_0.9-40             graph_1.74.0             
 [75] carData_3.0-5             Rhdf5lib_1.18.2          
 [77] zoo_1.8-11                beeswarm_0.4.0           
 [79] reprex_2.0.2              GlobalOptions_0.1.2      
 [81] pheatmap_1.0.12           ggridges_0.5.4           
 [83] processx_3.7.0            googlesheets4_1.0.1      
 [85] png_0.1-7                 viridisLite_0.4.1        
 [87] rjson_0.2.21              bitops_1.0-7             
 [89] KernSmooth_2.23-20        rhdf5filters_1.8.0       
 [91] Biostrings_2.64.1         blob_1.2.3               
 [93] DelayedMatrixStats_1.18.1 shape_1.4.6              
 [95] parallelly_1.32.1         spatstat.random_2.2-0    
 [97] rstatix_0.7.0             ggsignif_0.6.3           
 [99] beachmat_2.12.0           scales_1.2.1             
[101] memoise_2.0.1             GSEABase_1.58.0          
[103] ica_1.0-3                 zlibbioc_1.42.0          
[105] compiler_4.2.1            clue_0.3-61              
[107] fitdistrplus_1.1-8        snakecase_0.11.0         
[109] cli_3.4.1                 urlchecker_1.0.1         
[111] XVector_0.36.0            listenv_0.8.0            
[113] pbapply_1.5-0             ps_1.7.1                 
[115] MASS_7.3-57               mgcv_1.8-40              
[117] tidyselect_1.2.0          stringi_1.7.8            
[119] BiocSingular_1.12.0       ggrepel_0.9.1            
[121] fastmatch_1.1-3           tools_4.2.1              
[123] future.apply_1.9.1        parallel_4.2.1           
[125] circlize_0.4.15           rstudioapi_0.14          
[127] foreach_1.5.2             janitor_2.1.0            
[129] Rtsne_0.16                digest_0.6.29            
[131] rgeos_0.5-9               shiny_1.7.2              
[133] flexclust_1.4-1           car_3.1-0                
[135] broom_1.0.1               later_1.3.0              
[137] RcppAnnoy_0.0.19          httr_1.4.4               
[139] AnnotationDbi_1.58.0      colorspace_2.0-3         
[141] rvest_1.0.3               XML_3.99-0.11            
[143] fs_1.5.2                  tensor_1.5               
[145] reticulate_1.26           splines_4.2.1            
[147] uwot_0.1.14               rematch2_2.1.2           
[149] spatstat.utils_2.3-1      sessioninfo_1.2.2        
[151] plotly_4.10.0             xtable_1.8-4             
[153] jsonlite_1.8.2            modeltools_0.2-23        
[155] R6_2.5.1                  profvis_0.3.7            
[157] pillar_1.8.1              htmltools_0.5.3          
[159] mime_0.12                 glue_1.6.2               
[161] fastmap_1.1.0             BiocParallel_1.30.4      
[163] BiocNeighbors_1.14.0      class_7.3-20             
[165] codetools_0.2-18          pkgbuild_1.3.1           
[167] utf8_1.2.2                lattice_0.20-45          
[169] spatstat.sparse_2.1-1     ggbeeswarm_0.6.0         
[171] curl_4.3.3                leiden_0.4.3             
[173] colorway_0.2.0            shinyjs_2.1.0            
[175] survival_3.3-1            munsell_0.5.0            
[177] GetoptLong_1.0.5          GenomeInfoDbData_1.2.8   
[179] iterators_1.0.14          UCell_2.0.1              
[181] HDF5Array_1.24.2          haven_2.5.1              
[183] reshape2_1.4.4            spatstat.core_2.4-4 

```

**Comment by timoast** [comment] 2022-10-14 16:21
I'm not sure what the issue is here, I'd suggest reinstalling Rsamtools again and if that doesn't work reinstall R itself. I don't think this has anything to do with Signac, it's an issue with R finding the Rsamtools shared library

**Comment by pyrAmider** [comment] 2022-10-25 17:34
I had this issue as well.  It's caused by needing to have Rsamtools updated to the version appropriate for the R 4.2 environment, which it might not be if you've upgraded your R stack only recently.  

The solution for me was to re-install Rsamtools, but that comes with so many dependencies that I just updated my entire Bioconductor stack and called it a day.  Signac installed just fine after that.

**Comment by Dragonmasterx87** [comment] 2022-10-25 19:54
After R 4.2 a lot of bioconductor libraries have conflicts so doing what @pyrAmider did is actually necessary. In fact, you want to uninstall (or delete the lib folder) having older bioconductor libraries as I have seen some people have conflicts when R loads different libraries across versions. Reinstalling Rsamtools using the following also works for R 4.2

```
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("Rsamtools")
```

**Comment by timoast** [comment] 2022-10-25 20:15
That's good to know, I'll close this issue then

**Closed by timoast** 2022-10-25 20:15 UTC
Labels: installation

**Comment by roya-abs** [comment] 2022-10-28 13:44
Thanks all.
As you mentioned it was all about the R version. I installed R 4.0 (was the safest option for me) and could successfully install Signac.
